kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: queue-app
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - queue-app
  verbs:
  - use
