apiVersion: apps/v1
kind: Deployment
metadata:
    name: pong-queue
    labels:
      app: pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: queue-backend
        image: benjamintf1/queue-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: RESOURCE_COUNT
          value: "2"
        - name: PORT
          value: "8080"
      - name: queue-frontend
        image: benjamintf1/queue-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_SHOW_TIME_STARTED
          value: "true"
        - name: REACT_APP_HIGHLIGHT_TIME_STARTED_AFTER
          value: "20"
        - name: REACT_APP_API_URL
          value: " "


---
kind: Service
apiVersion: v1
metadata:
  name: pong
  annotations:
    cloud.google.com/app-protocols: '{"frontend":"HTTPS","frontend":"HTTP"}'
    service.alpha.kubernetes.io/app-protocols: '{"frontend":"HTTPS","frontend":"HTTP"}'
spec:
    type: NodePort
    selector:
      app: pong
    ports:
      - name: backend
        protocol: TCP
        port: 8081
        targetPort: 8080
      - name: frontend
        protocol: TCP
        port: 8080
        targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pong-ingress
  annotations:
        kubernetes.io/ingress.global-static-ip-name: pong-ip
spec:
  tls:
  - secretName: tls-secret
  backend:
    serviceName: pong
    servicePort: 8080
