apiVersion: apps/v1
kind: Deployment
metadata:
    name: pong-queue
    labels:
      app: pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: queue-backend
        image: benjamintf1/queue-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: RESOURCE_COUNT
          value: "2"
        - name: PORT
          value: "8080"
      - name: queue-frontend
        image: benjamintf1/queue-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_SHOW_TIME_STARTED
          value: "true"
        - name: REACT_APP_HIGHLIGHT_TIME_STARTED_AFTER
          value: "20"
        - name: REACT_APP_API_URL
          value: " "


---
kind: Service
apiVersion: v1
metadata:
    name: pong
spec:
    type: LoadBalancer
    selector:
      app: pong
    ports:
      - name: backend
        protocol: TCP
        port: 81
        targetPort: 8080
      - name: frontend
        protocol: TCP
        port: 80
        targetPort: 3000
