kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: queue-app
subjects:
- kind: ServiceAccount
  name: queue-app
  namespace: default
roleRef:
  kind: ClusterRole
  name: queue-app
  apiGroup: rbac.authorization.k8s.io

